### ISSUE TITLE
NullPointerException when running skeleton-namer v.1.5.5

### ISSUE THREAD

**Issue by kohearn-cwf** [Canadian-Wildlife-Federation/CHYF#19]
I am encountering a new error when running the latest version (1.5.5) of the skeleton namer. It seems to be related to the java.util.Map.size() method, I’ve attached a log for reference: [skeleton-namer_error.txt](https://github.com/Canadian-Wildlife-Federation/CHYF/files/9962960/skeleton-namer_error.txt). 

The full error message is:

```
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1803)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
        at java.base/java.util.HashMap.putMapEntries(HashMap.java:497)
        at java.base/java.util.HashMap.putAll(HashMap.java:785)
        at java.base/java.util.Collections$SynchronizedMap.putAll(Collections.java:2644)
        at ch.qos.logback.classic.util.LogbackMDCAdapter.setContextMap(LogbackMDCAdapter.java:197)
        at org.slf4j.MDC.setContextMap(MDC.java:264)
        at net.refractions.chyf.flowpathconstructor.skeletonizer.names.NameJob.run(NameJob.java:88)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        ... 3 more
```

I don’t think it’s a high priority for fixing as the 1.5.2 version of the skeleton namer / name engine still works fine, but I did want to flag this as an issue as I think this may be resulting from some of the changes made as part of https://github.com/Canadian-Wildlife-Federation/CHYF/commit/c9c5ee3f644d9b3827399d143133a914a3e40244.

**Comment by egouge** [comment]
Katherine, this is a bit weird - the error is happening when configuring the logging to include the workunit in the log file name. It's not happening all the time for you is it?  Was there something different about this run then some of the others?

**Comment by egouge** [comment]
OK that makes sense - next time I'm making updates to the tools I should be able to resolve this too.

**Comment by egouge** [comment]
This should be fixed in 1.5.6

**Comment by kohearn-cwf** [comment]
> This should be fixed in 1.5.6

I am still encountering this issue in 1.5.6, and confirmed with another team member that she gets the same error. Tested on 07EA005, 07EA0X4, and 07EB002. v.1.5.2 of the skeleton-namer still works, so we can continue to use this for now.

**Comment by egouge** [comment]
I missed on file - These tools should fix (1.5.7) it https://drive.google.com/file/d/1FDkfsY9If0N_xfMwOXERPfB6sYpY7lNW/view?usp=sharing

**Comment by kohearn-cwf** [comment]
> I missed one file - These tools should fix (1.5.7) it https://drive.google.com/file/d/1FDkfsY9If0N_xfMwOXERPfB6sYpY7lNW/view?usp=sharing

Thanks, confirming that fixed it! We will make sure to use v.1.5.7.
